title: ВиК услуги и ремонти гр.Русе - Мон груп
email: mongroup18@gmail.com
description: Водопроводни и канализационни услуги
destination: docs
# baseurl: "/mongroup"
# baseurl: ""
url: "https://vikruse.bg"
# url: ""
github_username: GerganaTsirkova
keywords: [Mongroup, Mon group, Mongrup, Mon grup, Монгруп, Мон груп, ВиК Русе, ViK Ruse]
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs,licence.txt]
# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
sass:
    style: compressed
