title: ВиК услуги и ремонти гр.Русе - Мон груп
email: mongroup18@gmail.com
description: Водопроводни и канализационни услуги
destination: docs
# baseurl: "/mongroup"
# baseurl: ""
url: "http://vikruse.bg"
github_username: GerganaTsirkova
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs,licence.txt]
# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
sass:
    style: compressed
