title: ВиК услуги и ремонти гр.Русе - Мон груп ЕООД
email: mongroup18@gmail.com
description: Фирма Мон груп предлага водопроводни и канализационни услуги и ремонти на територията на гр. Русе и околността
destination: docs
url: "https://vikruse.bg"
github_username: GerganaTsirkova
keywords: [Mongroup, Mon group, Mongrup, Mon grup, Монгруп, Мон груп, ВиК Русе, ViK Ruse]
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs,licence.txt]
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
sass:
    style: compressed
