title: ВиК услуги и ремонти гр.Русе - Мон груп
email: g_cirkova@mail.bg
description: Водопроводни и канализационни услуги
destination: docs
# baseurl: "/mongroup"
baseurl: ""
url: ""
twitter_username: GerganaTsirkova
github_username: GerganaTsirkova
exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, README.md,docs]
# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-sitemap
- github-pages
- jekyll-seo-tag
